[tool.black]
line-length = 240

[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "llava"
version = "1.7.0.dev1"
description = "VQToken on LLaVA-OneVision"
readme = "README.md"
requires-python = ">=3.10,<3.12"
license = "BSD-3-Clause AND Apache-2.0 AND MIT"
license-files = [
    "LICENSE",
    "THIRD_PARTY_NOTICES.md",
    "LICENSES/Apache-2.0.txt",
    "LICENSES/OpenAI-CLIP-MIT.txt",
    "LICENSES/lmms-eval-v0.2.4-LICENSE.txt",
]
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.optional-dependencies]
runtime = [
    "matplotlib",
    "requests",
    "scipy",
]

eval = [
    "shortuuid",
    "httpx==0.23.3",
    "einops",
    "ftfy",
    "accelerate==0.29.3",
    "av",
    "datasets==2.16.1",
    "decord",
    "einops==0.6.1",
    "einops-exts==0.0.4",
    "evaluate>=0.4.0",
    "hf_transfer",
    "jsonlines",
    "Jinja2",
    "loguru",
    "matplotlib",
    "mpmath",
    "nltk",
    "numexpr",
    "numpy==1.26.4",
    "open_clip_torch",
    "openai",
    "opencv-python-headless==4.9.0.80",
    "openpyxl",
    "packaging",
    "peft==0.4.0",
    "pillow",
    "protobuf==3.20",
    "pybind11>=2.6.2",
    "pycocoevalcap",
    "pydantic==1.10.8",
    "pytablewriter",
    "pyyaml",
    "requests",
    "sacrebleu>=1.5.0",
    "scikit-learn==1.2.2",
    "sentencepiece==0.1.99",
    "scipy",
    "sqlitedict==2.1.0",
    "sympy",
    "tenacity==8.3.0",
    "timm",
    "tiktoken",
    "torch==2.1.2",
    "torchvision==0.16.2",
    "tokenizers~=0.15.2",
    "tqdm-multiprocess",
    "transformers@git+https://github.com/huggingface/transformers.git@1c39974a4c4036fd641bc1191cc32799f85715a4",
    "transformers-stream-generator",
    "wandb>=0.16.0",
    "yt-dlp",
    "zss",
    "zstandard",
]

test = [
    "pytest>=8,<9",
    "torch==2.1.2",
]

[project.urls]
"Homepage" = "https://www.zhanghaichao.xyz/VQToken/"
"Repository" = "https://github.com/Hai-chao-Zhang/VQToken"

[tool.setuptools.packages.find]
include = ["llava*", "VQToken*"]
exclude = [
    "llava.eval*",
    "llava.serve*",
    "llava.train*",
    "llava.model.multimodal_encoder.eva_clip*",
    "llava.model.multimodal_encoder.dev_eva_clip*",
    "assets*",
    "benchmark*",
    "docs",
    "dist*",
    "playground*",
    "scripts*",
    "tests*",
    "checkpoints*",
    "project_checkpoints*",
    "debug_checkpoints*",
    "mlx_configs*",
    "wandb*",
    "notebooks*",
]

[tool.wheel]
exclude = [
    "assets*",
    "benchmark*",
    "docs",
    "dist*",
    "playground*",
    "scripts*",
    "tests*",
    "checkpoints*",
    "project_checkpoints*",
    "debug_checkpoints*",
    "mlx_configs*",
    "wandb*",
    "notebooks*",
]
